### ISSUE TITLE
Cannot build or run demo

### ISSUE THREAD

**Issue by chuckmitchell** [nstudio/nativescript-checkbox#103]
I cloned out the master branch on my machine and attempted to build the plugin and run the angular demo without any luck. It seems to fail on the build script.

 npm list | grep typescript
├── typescript@2.8.4

I cd to the src folder and run the following commands but get many Typescript compilation errors.

`npm i`
`npm run build` 

> nativescript-checkbox@3.0.3 build /private/tmp/nativescript-checkbox/src
> tsc

checkbox.android.ts(17,14): error TS2506: 'CheckBox' is referenced directly or indirectly in its own base expression.
checkbox.android.ts(106,21): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(109,9): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(121,16): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(125,9): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(133,10): error TS2339: Property '_context' does not exist on type 'CheckBox'.
checkbox.android.ts(211,12): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(212,36): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(215,13): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(216,9): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(219,34): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(221,25): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.android.ts(255,9): error TS2345: Argument of type '{ readonly owner: CheckBox; onCheckedChanged: (sender: CompoundButton, isChecked: boolean) => voi...' is not assignable to parameter of type '{ onCheckedChanged(param0: CompoundButton, param1: boolean): void; }'.
  Object literal may only specify known properties, and 'owner' does not exist in type '{ onCheckedChanged(param0: CompoundButton, param1: boolean): void; }'.
checkbox.android.ts(297,45): error TS2344: Type 'CheckBox' does not satisfy the constraint 'ViewBase'.
  Property 'left' is missing in type 'CheckBox'.
checkbox.android.ts(304,42): error TS2344: Type 'CheckBox' does not satisfy the constraint 'ViewBase'.
checkbox.ios.ts(12,14): error TS2506: 'CheckBox' is referenced directly or indirectly in its own base expression.
checkbox.ios.ts(124,8): error TS2339: Property 'addEventListener' does not exist on type 'CheckBox'.
checkbox.ios.ts(135,13): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.ios.ts(138,20): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.ios.ts(148,8): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.ios.ts(149,8): error TS2339: Property 'style' does not exist on type 'CheckBox'.
checkbox.ios.ts(171,8): error TS2339: Property 'nativeView' does not exist on type 'CheckBox'.
checkbox.ios.ts(195,8): error TS2339: Property 'removeEventListener' does not exist on type 'CheckBox'.
checkbox.ios.ts(222,13): error TS2339: Property 'nativeView' does not exist on type 'CheckBox'.
checkbox.ios.ts(302,38): error TS2344: Type 'CheckBox' does not satisfy the constraint 'ViewBase'.
checkbox.ios.ts(309,38): error TS2344: Type 'CheckBox' does not satisfy the constraint 'ViewBase'.
  Property 'left' is missing in type 'CheckBox'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! nativescript-checkbox@3.0.3 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the nativescript-checkbox@3.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/charles/.npm/_logs/2019-05-06T19_26_33_954Z-debug.log

**Comment by bradmartin** [comment]
fixed https://github.com/nstudio/nativescript-checkbox#running-demo-apps
