### ISSUE TITLE
android.support.v7.widget is undefined in {N} 6.0

### ISSUE THREAD

**Issue by tomfaltesek** [nstudio/nativescript-checkbox#113]
**Environment**
- CLI: 6.0.2
- tns-core-modules: 6.0.1
- nativescript-angular: 8.0.1
- Android Runtime: 6.0.0
- iOS Runtime:6.0.1

**Description**
After upgrading my project to NativeScript 6.0, if a `<CheckBox>` component is used in any of my templates, this exception is thrown:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: TypeError: Cannot read property 'widget' of undefined
System.err: 
System.err: StackTrace:
System.err: 	Frame: function:'push.../node_modules/nativescript-checkbox/checkbox.js.CheckBox.createNativeView', file:'file:///node_modules/nativescript-checkbox/checkbox.js:152:0
...
```

This is an issue on Android devices and emulators only.

**Steps to Reproduce**
Place a `<CheckBox>` in a template/view.

**Comment by marast78** [comment]
I have the same like @tomfaltesek

**Comment by classikd** [comment]
Thanks a lot @marast78

**Comment by MustafaCa** [comment]
Thanks for sharing!

**Comment by bradmartin** [comment]
Yes, the migration to androidX was breaking with this plugin and I didn't have time to make it super elegant 😞 so using the example on the README should work for the new packaged version under `@nstudio`

**Comment by MustafaCa** [comment]
On a second thought, I decided to use a Button and Label pair instead. This works without the dependency of a plug-in.

**Template code for  NS - vue**

            <StackLayout orientation="horizontal" horizontalAlignment="left">
              <Button class="mdi"  
                :text="String.fromCharCode( (saveFlag ? 0xf135 : 0xf131) )" 
                @tap="onSavePassword"/>
              <Label text=" Save password" />
            </StackLayout>

**JS method**

    onSavePassword() {
      this.saveFlag = !this.saveFlag
      console.log("Do something!")
    }

**CSS for the Material Design Icons**
`
.mdi {
    font-family: 'Material Design Icons';
}
`

**Comment by flipperlite** [comment]
This is an old thread but more clarification is needed. For NS6 projects, use the following:
```
tns plugin remove nativescript-checkbox
tns plugin add @nstudio/nativescript-checkbox@1.0.0
```
It seems to be plug and play with your old code that used `nativescript-checkbox`. For vanilla projects, change:
```
xmlns:CheckBox="nativescript-checkbox"
```
to
```
xmlns:CheckBox="@nstudio/nativescript-checkbox"
```
