### ISSUE TITLE
Is this plugin compatible with nativescript 7?

### ISSUE THREAD

**Issue by limux82** [nstudio/nativescript-checkbox#132]

**Comment by rickwalking** [comment]
I think... not yet.

**Comment by romandragan** [comment]
@limux82, @rickwalking, you can use https://www.npmjs.com/package/nativescript-checkbox-ns-7 for now – my temporary fork with NS 7 support.

**Comment by relez** [comment]
This is not working on my NS7/NG10 project, this is what I get on webpack compilation:

```
ERROR in node_modules/nativescript-checkbox-ns-7/angular/index.d.ts:14:22 - error NG6002: Appears in the NgModule.imports of InventoryModule, but could not be resolved to an NgModule class.

This likely means that the library (nativescript-checkbox-ns-7/angular) which declares TNSCheckBoxModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

14 export declare class TNSCheckBoxModule {
```

**Comment by BlueHunter99** [comment]
@nstudio are you planning on updating this or is this supposed to be a community effort?

**Comment by bradmartin** [comment]
Hey everyone, @lochstar provided the kick off to the NS7 support and `2.0.0` has been published. 
If any issues come up, feel free to open a new issue with stack traces, and all dep info so we can try to get it patched up.

@BlueHunter99 - we were trying to get around to it, just a lot of other plugins we've been trying to patch and submit PRs to other authors 😄 and this one was coming around on the list. However, any community PRs for updating plugins are always appreciated 👍

**Comment by BlueHunter99** [comment]
@bradmartin thank you guys very much for your hard work! I've been trying to get more into plugin development and have updated nativescript-plugin-badge for NS7 with nativescript-plugin-badge-ns-7 I'm happy with the direction NativeScript is going now that it's more focussed on Community
