### ISSUE TITLE
Android font size not working

### ISSUE THREAD

**Issue by JakubPawlak** [nstudio/nativescript-checkbox#73]
Hello,
Font size isn't applied on Android despite working properly on iOS, both in CSS stylesheet and as an inline xml property. Any idea why?
I'm using Nativescript 3.3.0 with Angular.

**Comment by geriskenderi** [comment]
I'm having the same problem essentially, only that the font-size isn't applied in android platform specific css. I don't know why but a lot of things go wrong with android, also the element alignment in some layouts like a horizontal stack layout

**Comment by isaacfi** [comment]
I have the same error :(

**Comment by shiv19** [comment]
How are you trying to set it?

Did you try setting

`fontSize="20"` directly on the element?

**Comment by isaacfi** [comment]
Yes I've noticed that works as property, but I need to resize the checkbox too. I downloaded your code and I implement the setScaleX and setScaleY, and I made it:

export const fillColorProperty = new CssProperty<Style, string>({
  name: "fillColor",
  cssName: "fill-color",
  valueConverter: v => {
    return String(v);
  }
});

**export const scaleProperty = new CssProperty<Style, string>({
  name: "scale",
  cssName: "scale",
  valueConverter: v => {
    return String(v);
  }
});**

export const tintColorProperty = new CssProperty<Style, string>({
  name: "tintColor",
  cssName: "tint-color",
  defaultValue: "#0075ff",
  valueConverter: v => {
    return String(v);
  }
});

then...

get fillColor(): string {
    return (<any>this.style).fillColor;
  }
  set fillColor(color: string) {
    (<any>this.style).fillColor = color;
    if (this._android && device.sdkVersion >= "21") {
      this._android.setButtonTintList(
        android.content.res.ColorStateList.valueOf(new Color(color).android)
      );
    }
  }

  **get scale(): string {
    return (<any>this.style).scale;
  }
  set scale(scale: string) {
    (<any>this.style).scale = scale;
    if (this._android) {
      this._android.setScaleX(java.lang.Float.parseFloat(scale));
      this._android.setScaleY(java.lang.Float.parseFloat(scale));
    }
  }**

  // there is no difference between tint and fill on the android widget
  get tintColor(): string {
    return (<any>this.style).fillColor;
  }

  set tintColor(color: string) {
    (<any>this.style).fillColor = color;
  }

and finally...


if (this._android) {
      if (this.fillColor) {
        android.support.v4.widget.CompoundButtonCompat.setButtonTintList(
          this._android,
          android.content.res.ColorStateList.valueOf(
            new Color(this.fillColor).android
          )
        );
      }
      **if (this.scale) {
        this._android.setScaleX(java.lang.Float.parseFloat(this.scale));
        this._android.setScaleY(java.lang.Float.parseFloat(this.scale));
      }**
    }

I don't know if this aproach can be doit in iOS.

Cheers

**Comment by fthuin** [comment]
If you want to change the text size only (on android), you can do something like this.

```
    onCheckboxLoaded(args) {
        const checkbox = <CheckBox>args.object;
        if (isAndroid) {
            checkbox.android.setTextSize(16);
        }
    }
```

```
<CheckBox #checkbox
    class="checkbox"
    [text]="answer.text"
    checked="false"
    boxType="circle"
    (tap)="onCheckboxTap($event, idx)"
    (checkedChange)="onCheckedChange()"
    fillColor="#0099cc"
    (loaded)="onCheckboxLoaded($event)"
></CheckBox>
```

**Comment by bearoutthere** [comment]
Got the same problem.  Tried "font-size" as per documentation and "fontSize"  to no avail.   The workaround above with the "setTextSize" in the onLoaded event works but feels hacky.   Standard styles should really work as they do on other components.
