### ISSUE TITLE
[feature] checkbox.setEnabled(false)

### ISSUE THREAD

**Issue by dali-gharbi** [nstudio/nativescript-checkbox#75]
Hi, I would like to disable the checkbox in certain condition after the checkedChange event 
my element 
```
    @ViewChild("actionStatusCheckbox") actionStatusCheckbox: ElementRef;

      let checkbox = this.actionStatusCheckbox.nativeElement;
```
is there any way to calll the android function "setEnabled(false)" and the ios property :

> Enabling / Disabling the Checkbox
> 
> The on Property
> 
> Just like UISwitch, BEMCheckBox provides the boolean property on that allows you to retrieve and set (without animation) a value determining wether the BEMCheckBox object is on or off. Defaults to NO.
> Example usage:
> 
> self.myCheckBox.on = YES;

**Comment by dali-gharbi** [comment]
actually there is already a solution using CheckedValueAccessor
```
let valueAccessor: CheckedValueAccessor = new CheckedValueAccessor(this.actionStatusCheckbox);
valueAccessor.setDisabledState(true);
```
(tested on android only)

**Comment by bradmartin** [comment]
Hi, there is a sample that should be working on the demo app here:
https://github.com/bradmartin/nativescript-checkbox/blob/master/demo/app/main-page.xml#L21
and code: https://github.com/bradmartin/nativescript-checkbox/blob/master/demo/app/main-page.ts#L28
