### ISSUE TITLE
Demo is not runing

### ISSUE THREAD

**Issue by OPADA-Eng** [nstudio/nativescript-checkbox#82]
I'm trying to deploy the demo to my emulator but it's not working.
it says: 
```
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
```
.
> Unable to apply changes on device: F6F1067A-E53F-4418-82C7-6B9DD680D31B. Error is: Processing node_modules failed. Error: cp: cannot create directory '/Users/username/Documents/projects/nativescript-checkbox/demo-ng/platforms/ios/demong/app/tns_modules': No such file or directory.

**Comment by shiv19** [comment]
Did you do `npm i` before trying to run the demo?

**Comment by OPADA-Eng** [comment]
Yes sure!

**Comment by iMarwan-k** [comment]
same massage with angular

**Comment by chuckmitchell** [comment]
Confirmed for angular.

1. Downloaded and unzipped Source Release.
1. ran `npm i`
1. ran `npm run demo.ng.android`

OUTPUT:

`npm run demo.ng.android`

> nativescript-checkbox@3.0.1 demo.ng.android /private/tmp/nativescript-checkbox-3.0.1
> npm run preparedemong && cd demo-ng && tns run android --emulator


> nativescript-checkbox@3.0.1 preparedemong /private/tmp/nativescript-checkbox-3.0.1
> npm run build && cd demo-ng && tns plugin remove nativescript-checkbox && tns plugin add .. && tns install


> nativescript-checkbox@3.0.1 build /private/tmp/nativescript-checkbox-3.0.1
> tsc

npm WARN deprecated @angular/http@4.1.3: Switch to @angular/common/http - see https://angular.io/guide/http

> nativescript-angular@3.0.0 postinstall /private/tmp/nativescript-checkbox-3.0.1/demo-ng/node_modules/nativescript-angular
> node postinstall.js


> nativescript-dev-typescript@0.4.6 postinstall /private/tmp/nativescript-checkbox-3.0.1/demo-ng/node_modules/nativescript-dev-typescript
> node postinstall.js

Project already targets TypeScript ~2.2.1
npm notice created a lockfile as package-lock.json. You should commit this file.
added 58 packages from 36 contributors and audited 80 packages in 10.181s
found 0 vulnerabilities

Successfully removed plugin nativescript-checkbox
+ nativescript-checkbox@3.0.1
added 1 package from 5 contributors and audited 80 packages in 2.411s
found 0 vulnerabilities

Successfully installed plugin nativescript-checkbox.
Copying template files...
Platform ios successfully added. v3.0.1
Copying template files...
Platform android successfully added. v3.2.0
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Found peer TypeScript 2.2.2
11:07:35 AM - Compilation complete. Watching for file changes.



Preparing project...
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Cycle link found.
Unable to apply changes on device: emulator-5554. Error is: Processing node_modules failed. Error: cp: cannot create directory '/private/tmp/nativescript-checkbox-3.0.1/demo-ng/platforms/android/src/main/assets/app/tns_modules': No such file or directory.

**Comment by chuckmitchell** [comment]
Extra info:
Node v10.15.3 LTS
npm v6.4.1

**Comment by bradmartin** [comment]
https://github.com/nstudio/nativescript-checkbox#running-demo-apps
