### ISSUE TITLE
ListView Checked Issue

### ISSUE THREAD

**Issue by horeyes** [nstudio/nativescript-checkbox#84]
Hello, I'm trying to use the checkbox on a RadListView and I can't get the checkbox state to change for each individual list item. It's only working for the first item in the list view, but any other item won't cause 
FirstCheckBox.nativeElement.checked property to change.

Here's my code: 

HTML:

    <ng-template let-item="item" let-i="index" let-odd="odd" let-even="even">
        <StackLayout>
          <GridLayout rows="90, auto, auto">
            <StackLayout rowSpan="2" backgroundColor="#BDBDBD"></StackLayout>
            <CheckBox #CB1 horizontalAlignment="Right" verticalAlignment="Top" (tap)="getCheckProp()" ></CheckBox>
            </StackLayout>
          </GridLayout>
        </StackLayout>
    </ng-template>

Typescript: 
```
 public getCheckProp() {
    console.log('checked prop value = ' + this.FirstCheckBox.nativeElement.checked);
  }
```

**Comment by horeyes** [comment]
Aight. Found a way to make it work.

**Comment by horeyes** [comment]
Hello, I found a way to make it work.

**Comment by cesarureno** [comment]
@horeyes Can you share your solution? please
