### ISSUE TITLE
checkedChange event not working on IOS

### ISSUE THREAD

**Issue by giorgi-abashidze** [nstudio/nativescript-checkbox#87]
checkedChange event not working on IOS, I don't know if it's working on android I'm testing it on ios and not working.

**Comment by andreacappadona17** [comment]
Having the same problem with Android.

Nativescript 4.1
nativescript-checkbox 3.0.3

**Comment by surdu** [comment]
Works fine in Android for me. Not working only in iOS.

**Comment by giorgi-abashidze** [comment]
anyone working to solve this?

**Comment by EddyVerbruggen** [comment]
Perhaps it's more constructive to channel that frustration towards providing a good example repo where the issue can be observed.

In the meanwhile, I'm using [this code](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/blob/ace8208d3936ddd660a71944e74bac33309599ba/app/input/input.component.html#L75) which seems to work just fine on both platforms (in this example I'm unchecking the other checkboxes to emulate radiobutton behavior).

Check the app in the [app stores (links here)](https://github.com/EddyVerbruggen/nativescript-pluginshowcase#nativescript-plugin-showcase) to see for yourself.

**Comment by giorgi-abashidze** [comment]
I'm creating checkboxes from js code and i'm trying to add checkedChange like this, but its not working.

(NativeScript Core)

`const myCheckBox2 = new CheckBox();

myCheckBox2.checkedChange=(args)=>{
                    console.log("check changed");
                };
`

**Comment by rigor789** [comment]
@giorgi-abashidze have you tried attaching it as an event listener? 

```
const myCheckBox2 = new CheckBox();
myCheckBox2.on('checkedChange', (args) => {
  console.log("check changed");
});
```

**Comment by giorgi-abashidze** [comment]
OMG I feel so stupid, thank you. I tried it but without  ' '  just checkedChange like this:
myCheckBox2.on(checkedChange, (args) => {
  console.log("check changed");
});
