### ISSUE TITLE
Can we have a 'readonly' property?

### ISSUE THREAD

**Issue by danvick** [nstudio/nativescript-checkbox#89]
Hi guys, first of all, Great Plugin! 
I'd like to request a '**readonly**' (or '**disabled**') property so that the Checkbox can be disabled. Thanks

**Comment by damianocorrado** [comment]
I join the request. It can be a very useful option.
Great job, thank you.

**Comment by shiv19** [comment]
Have you tried setting editable="false" on it?

**Comment by danvick** [comment]
@shiv19 `editable="false"` doesn't seem to be working

**Comment by shiv19** [comment]
Oh okay, not sure about it then.

**Comment by triniwiz** [comment]
You can try setting `isUserInteractionEnabled="false"` and `isEnabled="false"` on the checkbox to disable it
